/**
 * Integration test for the issue-#9 endpoints: uploads, entries (draft → poll
 * → save → delete), settings, export, and DELETE /account.
 *
 * The AI orchestrator pipeline is mocked at the module boundary
 * (`vi.mock('../../src/services/aiOrchestrator')`) so the test does NOT need
 * Azure OpenAI credentials. The blob backend is stubbed in-memory.
 *
 * Requires Docker for Postgres (or `PIXDIARY_TEST_DATABASE_URL`).
 */
import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest';
import { spawn, spawnSync } from 'node:child_process';
import { setTimeout as delay } from 'node:timers/promises';
import { randomUUID } from 'node:crypto';
import path from 'node:path';
import http, { type Server } from 'node:http';
import type { AddressInfo } from 'node:net';
import pgLib from 'pg';
import type { Pool } from 'pg';

import { resetConfigCache } from '../../src/config';
import { resetLoggerCache } from '../../src/log';
import { closePool, setPool } from '../../src/db/pool';
import { migrateUp } from '../../src/db/migrate';
import { setBlobBackend, type BlobBackend } from '../../src/services/blob';

// ----- Mock the orchestrator so route handlers don't fan out to Azure. -----
vi.mock('../../src/services/aiOrchestrator', async () => {
  const actual = await vi.importActual<typeof import('../../src/services/aiOrchestrator')>(
    '../../src/services/aiOrchestrator',
  );
  return {
    ...actual,
    /**
     * Replace the fire-and-forget pipeline. Synchronously flips status to
     * 'drafted' and writes a deterministic draft so the smoke test can
     * assert the polled entry shape.
     */
    startEntryPipeline: vi.fn(async (entryId: string) => {
      const { getPool } = await import('../../src/db/pool');
      await getPool().query(
        `UPDATE entries SET status = 'drafted', draft_md = $2 WHERE id = $1`,
        [entryId, '# Test draft\n\nGenerated by mocked orchestrator.'],
      );
    }),
  };
});

// ----- In-memory blob backend stub -----
function makeFakeBlob(): BlobBackend {
  const exists = new Set<string>();
  return {
    getContainerClient: async () => ({}) as never,
    issueUploadSas: async (blobPath: string) => {
      // Mark the blob as "uploaded" so the draft endpoint sees it.
      exists.add(blobPath);
      return {
        url: `https://fake.blob.core.windows.net/photos/${blobPath}?sv=fake`,
        expiresAt: new Date(Date.now() + 600_000),
      };
    },
    issueReadSas: async (blobPath: string) => ({
      url: `https://fake.blob.core.windows.net/photos/${blobPath}?sv=fake-read`,
      expiresAt: new Date(Date.now() + 600_000),
    }),
    exists: async (blobPath: string) => exists.has(blobPath),
    remove: async (blobPath: string) => {
      exists.delete(blobPath);
    },
    download: async () => Buffer.from(''),
  };
}

const MIGRATIONS_DIR = path.resolve(__dirname, '../../../database/migrations');
const PG_IMAGE = 'postgres:16-alpine';

interface TestPg {
  url: string;
  cleanup: () => Promise<void>;
}

function dockerAvailable(): boolean {
  if (process.env.PIXDIARY_TEST_DATABASE_URL) return false;
  const r = spawnSync('docker', ['version', '--format', '{{.Server.Version}}'], {
    encoding: 'utf8',
    timeout: 5_000,
  });
  return r.status === 0;
}

async function waitForPg(url: string, timeoutMs: number): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  let lastErr: unknown;
  while (Date.now() < deadline) {
    const probe = new pgLib.Pool({ connectionString: url, connectionTimeoutMillis: 1000 });
    try {
      await probe.query('SELECT 1');
      await probe.end();
      return;
    } catch (err) {
      lastErr = err;
      await probe.end().catch(() => undefined);
      await delay(500);
    }
  }
  throw new Error(`Postgres did not become ready in ${timeoutMs}ms: ${(lastErr as Error)?.message}`);
}

async function startDockerPg(): Promise<TestPg> {
  const containerName = `pixdiary-test-pg-${randomUUID().slice(0, 8)}`;
  const password = 'pixdiary-test';
  const port = 30000 + Math.floor(Math.random() * 20000);
  const args = [
    'run',
    '--rm',
    '-d',
    '--name',
    containerName,
    '-e',
    `POSTGRES_PASSWORD=${password}`,
    '-e',
    'POSTGRES_DB=pixdiary',
    '-p',
    `${port}:5432`,
    PG_IMAGE,
  ];
  const r = spawnSync('docker', args, { encoding: 'utf8' });
  if (r.status !== 0) {
    throw new Error(`docker run failed: ${r.stderr}`);
  }
  const url = `postgres://postgres:${password}@127.0.0.1:${port}/pixdiary`;
  try {
    await waitForPg(url, 60_000);
  } catch (err) {
    spawnSync('docker', ['rm', '-f', containerName]);
    throw err;
  }
  const cleanup = async (): Promise<void> => {
    await new Promise<void>((resolve) => {
      const c = spawn('docker', ['rm', '-f', containerName], { stdio: 'ignore' });
      c.on('exit', () => resolve());
      c.on('error', () => resolve());
    });
  };
  return { url, cleanup };
}

let pg: TestPg | undefined;
let server: Server | undefined;
let baseUrl = '';
let testPool: Pool | undefined;
const skip = !dockerAvailable() && !process.env.PIXDIARY_TEST_DATABASE_URL;

beforeAll(async () => {
  if (skip) return;

  if (process.env.PIXDIARY_TEST_DATABASE_URL) {
    pg = { url: process.env.PIXDIARY_TEST_DATABASE_URL, cleanup: async () => undefined };
  } else {
    pg = await startDockerPg();
  }

  process.env.NODE_ENV = 'test';
  process.env.DATABASE_URL = pg.url;
  process.env.JWT_SECRET = 'test-secret-test-secret-test-secret-test-secret';
  process.env.JWT_ACCESS_TTL_SECONDS = '900';
  process.env.JWT_REFRESH_TTL_SECONDS = '604800';
  process.env.BCRYPT_COST = '4';
  process.env.LOG_LEVEL = 'silent';
  // Lift rate limits high enough for the test sequence.
  process.env.RATE_LIMIT_GENERAL_PER_MIN = '10000';
  process.env.RATE_LIMIT_UPLOADS_PER_10MIN = '10000';
  process.env.RATE_LIMIT_DRAFTS_PER_HOUR = '10000';
  process.env.RATE_LIMIT_REGEN_PER_DAY = '10000';
  resetConfigCache();
  resetLoggerCache();

  testPool = new pgLib.Pool({ connectionString: pg.url });
  setPool(testPool);
  setBlobBackend(makeFakeBlob());

  await migrateUp({ migrationsDir: MIGRATIONS_DIR, pool: testPool });

  const { buildApp } = await import('../../src/app');
  const app = buildApp();
  server = http.createServer(app);
  await new Promise<void>((resolve) => server!.listen(0, '127.0.0.1', () => resolve()));
  const addr = server.address() as AddressInfo;
  baseUrl = `http://127.0.0.1:${addr.port}`;
}, 180_000);

afterAll(async () => {
  if (server) {
    await new Promise<void>((resolve) => server!.close(() => resolve()));
  }
  setBlobBackend(undefined);
  setPool(undefined);
  await closePool().catch(() => undefined);
  if (testPool) await testPool.end().catch(() => undefined);
  if (pg) await pg.cleanup();
}, 60_000);

interface AuthResp {
  accessToken: string;
  refreshToken: string;
  user: { id: string; email: string };
}

async function api(
  method: string,
  apiPath: string,
  body?: unknown,
  token?: string,
): Promise<{ status: number; body: unknown }> {
  const headers: Record<string, string> = { 'content-type': 'application/json' };
  if (token) headers.authorization = `Bearer ${token}`;
  const res = await fetch(`${baseUrl}${apiPath}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await res.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = text;
  }
  return { status: res.status, body: parsed };
}

async function signup(): Promise<{ token: string; userId: string; email: string; password: string }> {
  const email = `u-${Date.now()}-${Math.floor(Math.random() * 10000)}@example.com`;
  const password = 'a-good-password-1';
  const s = await api('POST', '/auth/signup', { email, password });
  expect(s.status).toBe(201);
  const r = s.body as AuthResp;
  return { token: r.accessToken, userId: r.user.id, email, password };
}

describe.skipIf(skip)('integration: full happy path (uploads → draft → poll → save → delete)', () => {
  it('signup → upload SAS → draft → poll → save → delete', async () => {
    const { token } = await signup();

    // 1. Issue upload SAS for one photo
    const up = await api(
      'POST',
      '/uploads',
      {
        entryDate: '2025-05-08',
        items: [
          { filename: 'a.jpg', mimeType: 'image/jpeg', sizeBytes: 12345 },
        ],
      },
      token,
    );
    expect(up.status).toBe(200);
    const upBody = up.body as { items: Array<{ photoId: string; sasUrl: string; blobPath: string }> };
    expect(upBody.items).toHaveLength(1);
    const photoId = upBody.items[0]!.photoId;
    expect(upBody.items[0]!.sasUrl).toContain('https://');

    // 2. Create draft (the fake blob backend already marked the path as uploaded)
    const dr = await api(
      'POST',
      '/entries/draft',
      { entryDate: '2025-05-08', photoIds: [photoId] },
      token,
    );
    expect(dr.status).toBe(202);
    const drBody = dr.body as { entryId: string; status: string };
    expect(drBody.entryId).toBeTruthy();
    expect(['pending', 'processing']).toContain(drBody.status);

    // 3. Poll until drafted (orchestrator mock flips status synchronously, but
    //    we still poll a few ticks because the route fires and forgets).
    let entry: { id: string; status: string; draftText: string | null } | undefined;
    for (let i = 0; i < 20; i++) {
      const get = await api('GET', `/entries/${drBody.entryId}`, undefined, token);
      expect(get.status).toBe(200);
      entry = get.body as typeof entry;
      if (entry!.status === 'drafted') break;
      await delay(50);
    }
    expect(entry?.status).toBe('drafted');
    expect(entry?.draftText).toContain('Test draft');

    // 4. Save final text
    const save = await api(
      'PUT',
      `/entries/${drBody.entryId}`,
      { text: 'My final diary entry. Today was great.' },
      token,
    );
    expect(save.status).toBe(200);
    const saved = save.body as { status: string; finalText: string };
    expect(saved.status).toBe('saved');
    expect(saved.finalText).toContain('Today was great');

    // 5. List shows the entry
    const list = await api('GET', '/entries', undefined, token);
    expect(list.status).toBe(200);
    const listBody = list.body as { items: Array<{ id: string }> };
    expect(listBody.items.some((e) => e.id === drBody.entryId)).toBe(true);

    // 6. Delete (soft-delete)
    const del = await api('DELETE', `/entries/${drBody.entryId}`, undefined, token);
    expect(del.status).toBe(204);

    // After delete, GET 404s
    const gone = await api('GET', `/entries/${drBody.entryId}`, undefined, token);
    expect(gone.status).toBe(404);
  }, 30_000);
});

describe.skipIf(skip)('integration: settings + export', () => {
  it('GET/PUT /settings round-trips, GET /export returns JSON dump', async () => {
    const { token } = await signup();

    const get1 = await api('GET', '/settings', undefined, token);
    expect(get1.status).toBe(200);
    const s1 = get1.body as { timezone: string; dailyCapEur: number };
    expect(typeof s1.timezone).toBe('string');
    expect(typeof s1.dailyCapEur).toBe('number');

    // Valid update
    const put1 = await api(
      'PUT',
      '/settings',
      { timezone: 'Europe/Copenhagen', dailyCapEur: 1.5 },
      token,
    );
    expect(put1.status).toBe(200);
    expect((put1.body as { dailyCapEur: number }).dailyCapEur).toBe(1.5);

    // Out-of-range cap fails validation
    const bad = await api('PUT', '/settings', { dailyCapEur: 99 }, token);
    expect(bad.status).toBe(400);

    // Bad timezone fails
    const badTz = await api('PUT', '/settings', { timezone: 'Not/A_Real_Zone' }, token);
    expect(badTz.status).toBe(400);

    // Empty patch is a 400 (zod refine rejects)
    const empty = await api('PUT', '/settings', {}, token);
    expect(empty.status).toBe(400);

    // Export
    const exp = await api('GET', '/export', undefined, token);
    expect(exp.status).toBe(200);
    const expBody = exp.body as { exportedAt: string; user: { email: string }; entries: unknown[] };
    expect(typeof expBody.exportedAt).toBe('string');
    expect(typeof expBody.user.email).toBe('string');
    expect(Array.isArray(expBody.entries)).toBe(true);
  }, 30_000);
});

describe.skipIf(skip)('integration: DELETE /account safety', () => {
  it('rejects without literal confirm string', async () => {
    const { token, password } = await signup();
    const r = await api('DELETE', '/account', { password, confirm: 'delete me please' }, token);
    expect(r.status).toBe(400);
  });

  it('rejects with wrong password (right confirm)', async () => {
    const { token } = await signup();
    const r = await api(
      'DELETE',
      '/account',
      { password: 'wrong-password-123456', confirm: 'DELETE MY ACCOUNT' },
      token,
    );
    expect(r.status).toBe(401);
  });

  it('rejects without auth token', async () => {
    const r = await api('DELETE', '/account', {
      password: 'whatever',
      confirm: 'DELETE MY ACCOUNT',
    });
    expect(r.status).toBe(401);
  });

  it('succeeds with literal confirm + correct password (account is gone)', async () => {
    const { token, password } = await signup();
    const ok = await api('DELETE', '/account', { password, confirm: 'DELETE MY ACCOUNT' }, token);
    expect(ok.status).toBe(204);

    // Subsequent /me with the (now stale) token should 401 — the user row is gone.
    const me = await api('GET', '/me', undefined, token);
    expect(me.status).toBe(401);
  }, 20_000);
});

describe.skipIf(skip)('integration: auth required on protected routes', () => {
  it('all protected endpoints reject missing tokens', async () => {
    const cases: Array<[string, string, unknown?]> = [
      ['POST', '/uploads', { entryDate: '2025-05-08', items: [] }],
      ['POST', '/entries/draft', { entryDate: '2025-05-08', photoIds: [] }],
      ['GET', '/entries'],
      ['GET', '/settings'],
      ['PUT', '/settings', { timezone: 'UTC' }],
      ['GET', '/export'],
      ['DELETE', '/account', { password: 'x', confirm: 'DELETE MY ACCOUNT' }],
    ];
    for (const [m, p, b] of cases) {
      const r = await api(m, p, b);
      expect(r.status, `${m} ${p}`).toBe(401);
    }
  });
});
